(cl:defpackage explorer-srv
  (:use )
  (:export
   "DISTANCE"
   "<DISTANCE-REQUEST>"
   "DISTANCE-REQUEST"
   "<DISTANCE-RESPONSE>"
   "DISTANCE-RESPONSE"
   "DISTANCEFROMROBOT"
   "<DISTANCEFROMROBOT-REQUEST>"
   "DISTANCEFROMROBOT-REQUEST"
   "<DISTANCEFROMROBOT-RESPONSE>"
   "DISTANCEFROMROBOT-RESPONSE"
   "GETCOST"
   "<GETCOST-REQUEST>"
   "GETCOST-REQUEST"
   "<GETCOST-RESPONSE>"
   "GETCOST-RESPONSE"
  ))

