(cl:defpackage fake_network-srv
  (:use )
  (:export
   "ROBOTPOSITION"
   "<ROBOTPOSITION-REQUEST>"
   "ROBOTPOSITION-REQUEST"
   "<ROBOTPOSITION-RESPONSE>"
   "ROBOTPOSITION-RESPONSE"
   "SENDMESSAGE"
   "<SENDMESSAGE-REQUEST>"
   "SENDMESSAGE-REQUEST"
   "<SENDMESSAGE-RESPONSE>"
   "SENDMESSAGE-RESPONSE"
  ))

